TP_Freelancer/TP_asp/FreeLance/FreeLance/Controllers/ClientsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FreeLance.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FreeLance.Controllers
{
    public class ClientsController : Controller
    {
        FreeDBContext ctx;

        public ClientsController(FreeDBContext ctx)
        {
            this.ctx = ctx;
        }

        //GET: ClientsController
        public ActionResult Index()
        {
            //ctx.Customers.Add(new Customer { Name = "Masoud", Email = "akam_50@yahoo.com" });
            IEnumerable<Customer> customers = ctx.Customers.ToList();
            return View("CustomersList", customers);
        }


        //public string Index()
        //{
        //    return "Clients";
        //}

        // GET: ClientsController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ClientsController/Create
        public ActionResult Create()
        {
            ViewBag.CatId = new SelectList(ctx.CustomersCats, "CatId", "CatName");
            return View();
        }

        // POST: ClientsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Customer customer)
        {
            
            try
            {
                if (ModelState.IsValid)
                {
                    ctx.Customers.Add(customer);
                    await ctx.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                ViewBag.CatId = new SelectList(ctx.CustomersCats, "CatId", "CatName");
                return View(customer);
            }
            catch
            {
                return View(customer);
            }
        }

        // GET: ClientsController/Edit/5
        public ActionResult Edit(int id)
        {
            Customer customer = ctx.Customers.SingleOrDefault(x => x.Id == id);
            return View("Edit",customer);
        }

        // POST: ClientsController/Edit/5


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Customer customer)
        {
            Customer customers = ctx.Customers.SingleOrDefault(x => x.Id == customer.Id);
            
            try
            {
                if (customers != null)
                {
                    customers.Name = customer.Name;
                    customers.Email = customer.Email;
                    ctx.SaveChanges();
                    
                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }



        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        // GET: ClientsController/Delete/5
        public ActionResult Delete(int id)
        {
            Customer customer = ctx.Customers.SingleOrDefault(x => x.Id == id);
            return View(customer);
        }

        // POST: ClientsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            Customer customer = ctx.Customers.SingleOrDefault(x => x.Id == id);
            
            try
            {
                ctx.Customers.Remove(customer);
                ctx.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }


        //======================================== Search Action ===================================

        public ActionResult SearchForName(string phrase)
        {
            var customer = from c in ctx.Customers where c.Name.Contains(phrase) select c;

            return View("Index", customer);
        }
    }
}

TP_Freelancer/TP_asp/FreeLance/FreeLance/Controllers/JobsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FreeLance.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace FreeLance.Controllers
{
    public class JobsController : Controller
    {

        FreeDBContext jctx;

        public JobsController(FreeDBContext jctx)
        {
            this.jctx = jctx;
        }
        // GET: JobsController
        public ActionResult Index()
        {
            //_context.Invoices.Include(x => x.Users).Include(x => x.Food).ToList();
            //Job job = jctx.Jobs.SingleOrDefault(j => j.JobId == id);
            //List<Job> jobs = jctx.Jobs.Include(x => x.JobState).Include(x => x.JobTitle).Include(x => x.JobStart).Include(x => x.JobEnd).Include(x => x.JobDescription).Include(x => x.CustomerId).ToList();



            List<Job> jobs = jctx.Jobs.ToList();
            return View(jobs);
        }

        // GET: JobsController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: JobsController/Create
        public ActionResult Create()
        {
            ViewBag.CustomerId = new SelectList(jctx.Customers, "Id", "Name");
            return View();
        }

        // POST: JobsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Job job)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    jctx.Jobs.Add(job);
                    jctx.SaveChanges();
                    return RedirectToAction(nameof(Index));
                }
                ViewBag.CustomerId = new SelectList(jctx.Customers, "Id", "Name", job.CustomerId);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(job);
            }
        }

        // GET: JobsController/Edit/5
        public ActionResult Edit(int id)
        {
            Job job = jctx.Jobs.SingleOrDefault(j => j.JobId == id);
            return View("Edit", job);
        }

        // POST: JobsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Job job)
        {
            Job jobs = jctx.Jobs.SingleOrDefault(j => j.JobId == id);
            try
            {
                if (jobs != null)
                {
                    jobs.JobState = job.JobState;
                    jobs.JobTitle = job.JobTitle;
                    jobs.JobStart = job.JobStart;
                    jobs.JobEnd = job.JobEnd;
                    jobs.JobDescription = job.JobDescription;
                    jctx.SaveChanges();
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: JobsController/Delete/5
        public ActionResult Delete(int id)
        {
            Job job = jctx.Jobs.SingleOrDefault(j => j.JobId == id);
            
            return View(job);
        }

        // POST: JobsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            Job job = jctx.Jobs.SingleOrDefault(j => j.JobId == id);
            try
            {
                jctx.Remove(job);
                jctx.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

TP_Freelancer/TP_asp/FreeLance/FreeLance/Controllers/QuotesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FreeLance.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FreeLance.Controllers
{
    public class QuotesController : Controller
    {

        FreeDBContext ctx;

        public QuotesController(FreeDBContext ctx)
        {
            this.ctx = ctx;
        }

        // GET: QuotesController
        public ActionResult Index()
        {
            List<Quote> quotes = ctx.Quotes.ToList();
            return View(quotes);
        }

        // GET: QuotesController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: QuotesController/Create
        public ActionResult Create()
        {
            ViewBag.JobId = new SelectList(ctx.Jobs, "JobId", "JobState"); 
            return View();
        }

        // POST: QuotesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Quote quote)
        {
            
            try
            {
                if (ModelState.IsValid)
                {
                ctx.Quotes.Add(quote);
                ctx.SaveChanges();
                return RedirectToAction(nameof(Index));
                }
                ViewBag.JobId = new SelectList(ctx.Jobs, "JobId", "JobState", quote.JobId);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(quote);
            }
        }

        // GET: QuotesController/Edit/5
        public ActionResult Edit(int id)
        {
            Quote quote = ctx.Quotes.SingleOrDefault(q => q.QuoteId == id);
            return View(quote);
        }

        // POST: QuotesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Quote quote)
        {
            Quote quotes = ctx.Quotes.SingleOrDefault(q => q.QuoteId == id);
            try
            {
                if(quotes != null)
                {
                    quotes.QuoteState = quote.QuoteState;
                    quotes.QuoteDate = quote.QuoteDate;
                    quotes.QuoteAmount = quote.QuoteAmount;
                    quotes.QuoteFinalDate = quote.QuoteFinalDate;
                    quotes.QuoteFinalAmount = quote.QuoteFinalAmount;
                    ctx.SaveChanges();
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: QuotesController/Delete/5
        public ActionResult Delete(int id)
        {
            Quote quote = ctx.Quotes.SingleOrDefault(q => q.QuoteId == id);
           
            return View("Delete", quote);
        }

        // POST: QuotesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            Quote quote = ctx.Quotes.SingleOrDefault(q => q.QuoteId == id);
            try
            {
                ctx.Remove(quote);
                ctx.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

TP_Freelancer/TP_asp/FreeLance/FreeLance/Views/Shared/_FreelanceLayout.cshtml
<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="~/css/main.css" rel="stylesheet" />
    <!--<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />-->
    <script src="https://kit.fontawesome.com/1df9e1fae9.js" crossorigin="anonymous"></script>
</head>

<body>
    <div class="container">
        <header>
            <a href ="@Url.Action("Index", "Home")"><img id="logo" src="~/TP_Freelancer_logo.jpg" /></a>
            <a class="headlink devis" href="@Url.Action("Index", "Quotes")"><i class="fas fa-calculator"> </i>  Devis & Factures</a>
            <a class="headlink mission" href="@Url.Action("Index", "Jobs")"><i class="fas fa-coffee"> </i>  Missions</a>
            <a class="headlink mission" href="@Url.Action("Index", "Clients")"><i class="fas fa-users"> </i>  Clients</a>
        </header>
        <br><br>

        @RenderBody()

        <footer>
            <p><i class="far fa-copyright"></i> Copyright 2021 <span class="point1">.</span> RAVANDOUST Masoud </p>
        </footer>

    </div>
    @RenderSection("Scripts", required: false)
</body>

</html>






@*<!DOCTYPE html>

    <html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>@ViewBag.Title</title>
    </head>
    <body>
        <div>
            @RenderBody()
        </div>
    </body>
    </html>*@

TP_Freelancer/TP_asp/FreeLance/FreeLance/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FreeLance</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FreeLance</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - FreeLance - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>